version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - node-1
      - node-2
      - node-3
    volumes:
      - ./nginx:/etc/nginx/conf.d/
  node-1:
    build: node
    ports:
      - 8081:8080
  node-2:
    build: node
    ports:
      - 8082:8080
  node-3:
    build: node
    ports:
      - 8083:8080
