version: '3'
services:
#  app:
#    build: app
#    ports:
#      - 8080:8080
  nginx:
    build: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/index.html:/etc/nginx/html/index.html
    ports:
    - 80:80

