version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: ecs-task-execution
  task_size:
    cpu_limit: 256
    mem_limit: 512
  services:
    app:
      essential: true

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-0b77f36f32f8fb8f1
        - subnet-0fe19f4f2764ab814
      security_groups:
        - sg-0abadf894b1a5a3fe