service: event-worker
provider:
  name: aws
  runtime: nodejs10.x
  stage: staging
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - sqs: arn:aws:sqs:ap-northeast-1:772010606571:ls-test-staging-queue
