version: '3'
services:
  root:
    image: scatter-gather
    container_name: root_node
    environment:
      - SERVER_TYPE=root
      - PORT=5000
      - NODE_ID=0
    volumes:
      - .:/app:ro
    ports:
      - 5000:5000

  leaf1:
    image: scatter-gather
    container_name: leaf1_node
    environment:
      - SERVER_TYPE=leaf
      - PORT=5001
      - NODE_ID=1
    volumes:
      - .:/app:ro
    ports:
      - 5001:5001

  leaf2:
    image: scatter-gather
    container_name: leaf2_node
    environment:
      - SERVER_TYPE=leaf
      - PORT=5002
      - NODE_ID=2
    volumes:
      - .:/app:ro
    ports:
      - 5002:5002
