apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  # type: ExternalName
  # externalName: gihyo-docker
  selector:
    app: echo
    release: summer
  ports:
    - name: http
      port: 80

